[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rompy_xbeach"
description = "Rompy Xbeach Config package."
readme = "README.rst"
authors = [
  {name = "Rompy Developers", email = "developers@rompy.com"}
]
maintainers = [
  {name = "Rompy Developers", email = "developers@rompy.com"}
]
classifiers = [

]
license = {text = "BSD 3-Clause License"}
dependencies = [
  "pydantic-numpy",
  "rioxarray",
  "rompy",
  "oceantide",
  "typer",
]
dynamic = ["version"]

[project.optional-dependencies]
extra = [
  "rompy-binary-datasources",
]
dev = [
  "coverage",
  "mypy",
  "pytest",
  "ruff",
]
docs = [
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs-jupyter",
]

[project.scripts]
rompy_xbeach = "rompy_xbeach.cli:app"

[project.entry-points."rompy.config"]
xbeach = "rompy_xbeach.config:Config"

[project.entry-points."xbeach.data"]
"wind_grid:wind" = "rompy_xbeach.data.wind:WindGrid"
"wind_station:wind" = "rompy_xbeach.data.wind:WindStation"
"wind_point:wind" = "rompy_xbeach.data.wind:WindPoint"
"tide_cons_grid:tide" = "rompy_xbeach.data.waterlevel:TideConsGrid"
"tide_cons_point:tide" = "rompy_xbeach.data.waterlevel:TideConsPoint"
"water_level_grid:tide" = "rompy_xbeach.data.waterlevel:WaterLevelGrid"
"water_level_station:tide" = "rompy_xbeach.data.waterlevel:WaterLevelStation"
"water_level_point:tide" = "rompy_xbeach.data.waterlevel:WaterLevelPoint"
"boundary_station_spectra_jons:wave" = "rompy_xbeach.data.boundary:BoundaryStationSpectraJons"
"boundary_station_param_jons:wave" = "rompy_xbeach.data.boundary:BoundaryStationParamJons"
"boundary_grid_param_jons:wave" = "rompy_xbeach.data.boundary:BoundaryGridParamJons"
"boundary_point_param_jons:wave" = "rompy_xbeach.data.boundary:BoundaryPointParamJons"
"boundary_station_spectra_jonstable:wave" = "rompy_xbeach.data.boundary:BoundaryStationSpectraJonstable"
"boundary_station_param_jonstable:wave" = "rompy_xbeach.data.boundary:BoundaryStationParamJonstable"
"boundary_grid_param_jonstable:wave" = "rompy_xbeach.data.boundary:BoundaryGridParamJonstable"
"boundary_point_param_jonstable:wave" = "rompy_xbeach.data.boundary:BoundaryPointParamJonstable"
"boundary_station_spectra_swan:wave" = "rompy_xbeach.data.boundary:BoundaryStationSpectraSwan"
"stat:wave" = "rompy_xbeach.data.boundary:BoundaryStat"
"bichrom:wave" = "rompy_xbeach.data.boundary:BoundaryBichrom"
"file_stat_table:wave" = "rompy_xbeach.data.boundary:BoundaryStatTable"
"file_ts_1:wave" = "rompy_xbeach.data.boundary:BoundaryTs1"
"file_ts_2:wave" = "rompy_xbeach.data.boundary:BoundaryTs2"
"file_ts_nonh:wave" = "rompy_xbeach.data.boundary:BoundaryTsNonh"
"off:wave" = "rompy_xbeach.data.boundary:BoundaryOff"
"reuse:wave" = "rompy_xbeach.data.boundary:BoundaryReuse"
"file_jons:wave" = "rompy_xbeach.data.boundary:BoundaryFileJons"
"file_jonstable:wave" = "rompy_xbeach.data.boundary:BoundaryFileJonstable"
"file_swan:wave" = "rompy_xbeach.data.boundary:BoundaryFileSwan"

[project.entry-points."xbeach.source"]
"geotiff:crs" = "rompy_xbeach.source:SourceGeotiff"
"xyz:crs" = "rompy_xbeach.source:SourceXYZ"
"dataset:crs" = "rompy_xbeach.source:SourceCRSDataset"
"file:crs" = "rompy_xbeach.source:SourceCRSFile"
"intake:crs" = "rompy_xbeach.source:SourceCRSIntake"
"tide_cons_point_csv:tide_cons_point" = "rompy_xbeach.source:SourceTideConsPointCSV"

[project.entry-points."xbeach.interpolator"]
regular_grid = "rompy_xbeach.interpolate:RegularGridInterpolator"

[project.urls]
bugs = "https://github.com/rom-py/rompy_xbeach/issues"
changelog = "https://github.com/rom-py/rompy_xbeach/blob/master/changelog.md"
homepage = "https://github.com/rom-py/rompy_xbeach"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]
"rompy_xbeach" = ["templates/**/*", "templates/**/.*"]

[tool.setuptools.dynamic]
version = {attr = "rompy_xbeach.__version__"}

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:numpy.ndarray size changed:RuntimeWarning",
]