"""Check that an XBeach image runs workspaces generated by rompy-xbeach.

Generates two short models from the test data, one stationary with constant waves
and one surfbeat with a JONSWAP boundary, runs each in the image serially, and
runs the surfbeat model with MPI as well.

Usage: python docker/test_image.py <image>
"""

import subprocess
import sys
import tempfile
from pathlib import Path

from rompy.core.time import TimeRange
from rompy.model import ModelRun

from rompy_xbeach.components.boundary.parameters import TideBoundaryConditions
from rompy_xbeach.components.output import Output
from rompy_xbeach.components.physics import Physics
from rompy_xbeach.components.physics.wavemodel import Stationary, Surfbeat
from rompy_xbeach.config import Config, DataInterface
from rompy_xbeach.data.bathy import SeawardExtensionLinear, XBeachBathy
from rompy_xbeach.data.boundary import BoundaryParams, BoundaryStationSpectraJons
from rompy_xbeach.grid import RegularGrid
from rompy_xbeach.source import SourceCRSWavespectra, SourceGeotiff

DATA = Path(__file__).resolve().parents[1] / "tests" / "data"
DIRECTIONS = {"thetamin": -90.0, "thetamax": 90.0, "dtheta": 15.0, "dtheta_s": 10.0}


def config(wavemodel, wave):
    """A small model of the test beach with the given wave model and boundary."""
    return Config(
        grid=RegularGrid(
            ori={"x": 115.594239, "y": -32.641104, "crs": 4326},
            alfa=347.0,
            dx=20.0,
            dy=30.0,
            nx=115,
            ny=110,
            crs=28350,
        ),
        bathy=XBeachBathy(
            source=SourceGeotiff(filename=DATA / "bathy.tif"),
            posdwn=False,
            extension=SeawardExtensionLinear(depth=15.0, slope=0.05),
        ),
        input=DataInterface(wave=wave),
        physics=Physics(wavemodel=wavemodel),
        tide_boundary=TideBoundaryConditions(tideloc=0, zs0=0.0),
        output=Output(globalvars=["H", "zs"], tintg=300.0),
    )


CASES = {
    "stationary": config(
        Stationary(), BoundaryParams(Hrms=1.0, Trep=10.0, **DIRECTIONS)
    ),
    "surfbeat": config(
        Surfbeat(),
        BoundaryStationSpectraJons(
            source=SourceCRSWavespectra(
                uri=DATA / "ww3-spectra-20230101-short.nc", reader="read_ww3"
            ),
            location="offshore",
            sel_method="nearest",
            **DIRECTIONS,
        ),
    ),
}
COMMANDS = {
    "stationary": ["xbeach"],
    "surfbeat": ["xbeach"],
    "surfbeat-mpi": [
        "mpirun",
        "--allow-run-as-root",
        "--oversubscribe",
        "-n",
        "3",
        "xbeach",
    ],
}


def main(image: str) -> int:
    period = TimeRange(start="2023-01-01T00:00", end="2023-01-01T00:05", interval="5m")
    failed = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, command in COMMANDS.items():
            case = name.split("-")[0]
            run = ModelRun(
                run_id=name, period=period, output_dir=tmp, config=CASES[case]
            )
            workspace = Path(run()).resolve()
            result = subprocess.run(
                ["docker", "run", "--rm", "-v", f"{workspace}:/data", image, *command],
                capture_output=True,
                text=True,
            )
            ok = result.returncode == 0 and (workspace / "xboutput.nc").exists()
            print(f"{name}: {'OK' if ok else 'FAILED'}")
            if not ok:
                print(result.stdout[-2000:], result.stderr[-2000:])
                failed.append(name)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
