name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Publish Python Package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rompy-xbeach
    permissions:
      id-token: write
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip build
        pip install .[dev]
    -
      name: Test package
      run: pytest -s -v tests
    -
      name: Build package
      run: python -m build
    -
      name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
